## <font color='DE1509'>การสุ่มตัวอย่าง</font>

ในบทนี้ชุดข้อมูลที่ใช้คือ "titanic.csv" ซึ่งเป็นข้อมูลของผู้โดยสารเรือไททานิคมีรายละเอียดของแต่ละคอลัมน์ดังนี้:

PassengerId: ID ของผู้โดยสาร
Survived: ผู้โดยสารรอด (1) หรือเสียชีวิต (0)  
Pclass: ชนชั้นของผู้โดยสาร first class (1), second class (2), thrid class (3)  
Name: ชื่อ-สกุล  
Sex: เพศ    
Age: อายุ  
SibSp: จำนวนพี่น้อง (siblings) และคู่สมรส (spouse) ที่เดินทางมาด้วย    
Parch:  จำนวนบิดา-มารดา (parent) และบุตร (child) ที่เดินทางมาด้วย  
Ticket: รหัสตั๋วโดยสาร  
Fare: ค่าตั๋วโดยสาร  
Cabin: รหัสห้องผู้โดยสาร  
Embarked: ท่าเรือต้นทาง Southampton (S), Cherbourg (C), และ Queenstown (Q)

\*\*วิธีการต่างๆที่แสดงในบทเรียนนี้เป็นเพียงแค่การยกตัวอย่างเท่านั้น ในการนำไปใช้จริงประชากรควรมีจำนวนมากกว่าชุดข้อมูลที่นำมาเป็นตัวอย่างนี้

\
ทำการ import library ที่ต้องใช้:

In [1]:
import numpy as np #สำหรับการจัดการข้อมูลที่เป็นตัวเลขต่างๆ
import pandas as pd #สำหรับอ่านข้อมูลให้อยู่ในรูปแบบ dataframe
import matplotlib.pyplot as plt #เพื่อใช้ควบคู่กับ seaborn ในการทำ data visualization
import seaborn as sns #สำหรับการทำ data visualization

\
อ่านข้อมูลจากไฟล์ให้อยู่ในรูปแบบ dataframe และแสดงข้อมูล 5 แถวแรก:

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/ThammakornS/ProgStat/main/dataset/titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

\
ดูภาพรวมข้อมูลเบื้องต้น:

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

\
เนื่องจากในบทนี้จะใช้ข้อมูลอายุเป็นหลัก จึงต้องกรองให้มีเฉพาะผู้โดยสารที่มีข้อมูลอายุเท่านั้น:

In [4]:
df_age = df[df.Age.notnull()]
df_age.info()

<class 'pandas.core.frame.DataFrame'>
Index: 714 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  714 non-null    int64
 1   Survived     714 non-null    int64
 2   Pclass       714 non-null    int64
 3   Name         714 non-null    object
 4   Sex          714 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        714 non-null    int64
 7   Parch        714 non-null    int64
 8   Ticket       714 non-null    object
 9   Fare         714 non-null    float64
 10  Cabin        185 non-null    object
 11  Embarked     712 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 72.5+ KB

&nbsp;  
#### 1. เลือกตัวอย่างขนาด n = 100 โดยใช้การสุ่มตัวอย่างแบบง่าย (simple random sampling)

In [6]:
sample_simple_rand = df_age.sample(n=100)
sample_simple_rand.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.775,NaN,S
841,842,0,2,"Mudd, Mr. Thomas Charles",male,16.0,0,0,S.O./P.P. 3,10.500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.000,C148,C
761,762,0,3,"Nirva, Mr. Iisakki Antino Aijo",male,41.0,0,0,SOTON/O2 3101272,7.125,NaN,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.750,NaN,Q

\
หาค่าเฉลี่ยอายุจากตัวอย่างที่ได้:

In [7]:
sample_simple_rand.Age.mean()

30.9825

In [8]:
f"ค่าเฉลี่ยอายุตัวอย่าง = {sample_simple_rand.Age.mean(): .2f} ± {sample_simple_rand.Age.std(): .2f}"

'ค่าเฉลี่ยอายุตัวอย่าง =  30.98 ±  14.59'

\
ค่าเฉลี่ยอายุของประชากร:

In [11]:
df_age.Age.mean()

29.69911764705882

In [10]:
f"ค่าเฉลี่ยอายุประชากร = {df_age.Age.mean(): .2f} ± {df_age.Age.std(): .2f}"

'ค่าเฉลี่ยอายุประชากร =  29.70 ±  14.53'

\
การกำหนดเลขสุ่มเพื่อให้สามารถทำการทดลองซ้ำได้

In [14]:
sample_simple_rand = df_age.sample(n=100, random_state=123)

In [15]:
sample_simple_rand.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
651,652,1,2,"Doling, Miss. Elsie",female,18.0,0,1,231919,23.0000,NaN,S
694,695,0,1,"Weir, Col. John",male,60.0,0,0,113800,26.5500,NaN,S
797,798,1,3,"Osman, Mrs. Mara",female,31.0,0,0,349244,8.6833,NaN,S
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.0,1,0,PC 17758,108.9000,C65,C

&nbsp;  
#### 2. เลือกตัวอย่างขนาด n = 100 โดยใช้การสุ่มตัวอย่างแบบมีระบบ (systematic sampling)

\
หาขนาดช่วงการสุ่ม I:

In [16]:
I = (int)(df_age.shape[0]/100)
I

7

\
index ของแถวที่เลือกเป็นช่วงตามค่า I โดยใช้ค่า r = 1 (index แรก = 0):

In [17]:
sel_idx = np.arange(start=0, stop=df_age.shape[0], step=I)
sel_idx

array([  0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,
        91,  98, 105, 112, 119, 126, 133, 140, 147, 154, 161, 168, 175,
       182, 189, 196, 203, 210, 217, 224, 231, 238, 245, 252, 259, 266,
       273, 280, 287, 294, 301, 308, 315, 322, 329, 336, 343, 350, 357,
       364, 371, 378, 385, 392, 399, 406, 413, 420, 427, 434, 441, 448,
       455, 462, 469, 476, 483, 490, 497, 504, 511, 518, 525, 532, 539,
       546, 553, 560, 567, 574, 581, 588, 595, 602, 609, 616, 623, 630,
       637, 644, 651, 658, 665, 672, 679, 686, 693, 700, 707])

\
ตรวจสอบจำนวนตัวอย่างที่ได้:

In [18]:
len(sel_idx)

102

\
เนื่องจากจำนวนตัวอย่างเกินมา 2 จะตัดให้เหลือ 100 เท่านั้น:

In [19]:
sel_idx = sel_idx[0:100]
len(sel_idx)

100

\
เลือกตัวอย่าง:

In [20]:
sel_boo = np.isin(df_age.index, sel_idx)
sel_boo

array([ True, False, False, False, False, False,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False,  True,
       False, False, False, False, False,  True, False, False, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False, False, False, False,  True, False, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False, False,  True, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False,  True, False, False, False,  True,
       False, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False,  True, False, False, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False,  True, False, False, False,
       False, False, False,  True, False, False, False, False, False,
        True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False,  True, False, False, False, False,
       False,  True, False, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False,  True, False, False, False,  True,
       False, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
        True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [21]:
sample_sys_rand = df_age[sel_boo]
#sample_sys_rand = df_age.iloc[sel_idx,]
sample_sys_rand.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S

\
หาค่าเฉลี่ยอายุจากตัวอย่างที่ได้:

In [22]:
sample_sys_rand.Age.mean()

28.403614457831324

In [23]:
print(f"ค่าเฉลี่ยอายุตัวอย่าง = {sample_sys_rand.Age.mean(): .2f} ± {sample_sys_rand.Age.std(): .2f}")
print(f"ค่าเฉลี่ยอายุประชากร = {df_age.Age.mean(): .2f} ± {df_age.Age.std(): .2f}")

ค่าเฉลี่ยอายุตัวอย่าง =  28.40 ±  15.44
ค่าเฉลี่ยอายุประชากร =  29.70 ±  14.53

&nbsp;  
#### 3. เลือกตัวอย่างขนาด n = 100 โดยใช้การสุ่มตัวอย่างแบบชั้นภูมิ (stratified sampling)

ในที่นี้จะแบ่งชั้นภูมิตามคอลัมน์ Pclass ดังนั้นจะแบ่งได้ 3 ชั้นภูมิ  
เบื้องต้นหาจำนวนผู้โดยสารของแต่ละชั้นภูมิ:

In [24]:
df_age.Pclass.value_counts()

Pclass
3    355
1    186
2    173
Name: count, dtype: int64

จะเห็นได้ว่าผู้โดยสาร Pclass=3 มีจำนวนมากกว่า 1 และ 2  
หากคิดเป็นร้อยละของจำนวนตัวอย่างในแต่ละ Pclass จะได้ว่า:

In [27]:
np.round(df_age.Pclass.value_counts()/df_age.shape[0] * 100)

Pclass
3    50.0
1    26.0
2    24.0
Name: count, dtype: float64

\
เนื่องจากเป้าหมายต้องการตัวอย่างขนาด n = 100 จะต้องทำการสุ่มเลือกหน่วยตัวอย่างจาก Pclass 1, 2 และ 3 จำนวน 24, 21 และ 55 หน่วยตัวอย่างตามลำดับ:

In [25]:
sample_strat_pclass = pd.concat([
    df[df['Pclass']==1].sample(n=26),
    df[df['Pclass']==2].sample(n=24),
    df[df['Pclass']==3].sample(n=50)
])
sample_strat_pclass.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 621 to 858
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  100 non-null    int64
 1   Survived     100 non-null    int64
 2   Pclass       100 non-null    int64
 3   Name         100 non-null    object
 4   Sex          100 non-null    object
 5   Age          83 non-null     float64
 6   SibSp        100 non-null    int64
 7   Parch        100 non-null    int64
 8   Ticket       100 non-null    object
 9   Fare         100 non-null    float64
 10  Cabin        28 non-null     object
 11  Embarked     100 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 10.2+ KB

\
หาค่าเฉลี่ยอายุจากตัวอย่างที่ได้:

In [26]:
sample_strat_pclass.Age.mean()

29.543253012048194

In [27]:
print(f"ค่าเฉลี่ยอายุตัวอย่าง = {sample_strat_pclass.Age.mean(): .2f} ± {sample_sys_rand.Age.std(): .2f}")
print(f"ค่าเฉลี่ยอายุประชากร = {df.Age.mean(): .2f} ± {df.Age.std(): .2f}")

ค่าเฉลี่ยอายุตัวอย่าง =  29.54 ±  15.44
ค่าเฉลี่ยอายุประชากร =  29.70 ±  14.53

&nbsp;  
#### 4. เลือกตัวอย่างโดยใช้การสุ่มตัวอย่างแบบกลุ่ม (cluster sampling)

การเลือกแบบนี้จะทำการกำหนดขนาด n ไม่ได้เนื่องจากต้องเลือกทั้งกลุ่ม
ในที่นี้จะแบ่งกลุ่มตามคอลัมน์ Pclass ดังนั้นจะแบ่งได้ 3 กลุ่ม  
และเลือกกลุ่ม Pclass 1, 2 หรือ 3 ทั้งกลุ่ม:

In [28]:
df_age.Pclass.value_counts()

Pclass
3    355
1    186
2    173
Name: count, dtype: int64

ทำการสุ่มมา 1 กลุ่มแล้วเลือกตัวอย่างทั้งกลุ่มจากที่สุ่มมา

In [29]:
import random
sel_pclass = random.randint(1,3)
print(sel_pclass)

1

In [30]:
sample_cluster = df_age[df_age.Pclass==sel_pclass]

\
หาค่าเฉลี่ยอายุจากตัวอย่างที่ได้:

In [31]:
print(f"ค่าเฉลี่ยอายุตัวอย่าง = {sample_cluster.Age.mean(): .2f} ± {sample_cluster.Age.std(): .2f}")
print(f"ค่าเฉลี่ยอายุประชากร = {df_age.Age.mean(): .2f} ± {df_age.Age.std(): .2f}")

ค่าเฉลี่ยอายุตัวอย่าง =  38.23 ±  14.80
ค่าเฉลี่ยอายุประชากร =  29.70 ±  14.53

\
หากสุ่มได้ Pclass=3:

In [32]:
sample_cluster_pclass3 = df_age[df_age.Pclass==3]
print(f"ค่าเฉลี่ยอายุตัวอย่าง = {sample_cluster_pclass3.Age.mean(): .2f} ± {sample_cluster_pclass3.Age.std(): .2f}")
print(f"ค่าเฉลี่ยอายุประชากร = {df_age.Age.mean(): .2f} ± {df_age.Age.std(): .2f}")

ค่าเฉลี่ยอายุตัวอย่าง =  25.14 ±  12.50
ค่าเฉลี่ยอายุประชากร =  29.70 ±  14.53

\
หากสุ่มได้ Pclass=1:

In [38]:
sample_cluster_pclass1 = df_age[df_age.Pclass==1]
print(f"ค่าเฉลี่ยอายุตัวอย่าง = {sample_cluster_pclass1.Age.mean(): .2f} ± {sample_cluster_pclass1.Age.std(): .2f}")
print(f"ค่าเฉลี่ยอายุประชากร = {df_age.Age.mean(): .2f} ± {df_age.Age.std(): .2f}")

ค่าเฉลี่ยอายุตัวอย่าง =  38.23 ±  14.80
ค่าเฉลี่ยอายุประชากร =  29.70 ±  14.53

\
จะเห็นได้ว่าการเลือก Pclass=1 และ 3 ค่าเฉลี่ยอายุจะมีความคลาดเคลื่อนจากประชากรค่อนข้างมาก